export const SUPER_ADMIN_ROUTES = {
  DASHBOARD: "/super-admin/dashboard",
  USERS: "/super-admin/users",
  AUDIT: "/super-admin/audit",
  BILLING: "/super-admin/billing",
  SETTINGS: "/super-admin/settings",
  ANALYTICS: "/super-admin/analytics",
  HOTEL_LIST: "/super-admin/hotels",
  SUBSCRIPTION_PLAN: "/super-admin/subscriptions",
  BACKUP: "/super-admin/backup",
  PAYMENTS: "/super-admin/payments",
  REQUESTS: "/super-admin/requests",
  DATA: "/super-admin/data",
  COUPONS: "/super-admin/coupons",
  AFFILIATES: "/super-admin/affiliates",
  BROADCASTS: "/super-admin/broadcasts",
  FEATURES: "/super-admin/features",
  INFRASTRUCTURE: "/super-admin/infrastructure",
  SYSTEM: "/super-admin/system",
  JOBS: "/super-admin/jobs",
  MIGRATIONS: "/super-admin/migrations",
  TICKETS: "/super-admin/tickets",
} as const;
